spring:
  liquibase:
    change-log: classpath:/db/changelog/master.yaml

dinghysearch:
  cache:
    ttl: 5000

logging:
  level:
    org:
      schweben:
        dinghyapi:
          mappers: DEBUG

server:
  protocol: http
  address: localhost
  port: 8080
